export { router as loginRouter } from './login'
export { router as logOutRouter } from './logout'
export { router as userRouter } from './user'
export { router as updateDailyCustomerRouter } from './updateDailyCustomer'
export { router as customerRouter} from './customer'